# Generated by Django 2.2 on 2019-04-30 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
